# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/clusters_curso_nbdev',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/clusters_curso_nbdev',
                'lib_path': 'clusters_curso_nbdev'},
  'syms': {'clusters_curso_nbdev.core': {'clusters_curso_nbdev.core.foo': ('core.html#foo', 'clusters_curso_nbdev/core.py')}}}
