# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_geoespatial.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_geoespatial.ipynb 2
from .cluster_ejemplo import *
import numpy as np
import shapely
from shapely.ops import unary_union
